# Generated by Django 5.2.6 on 2025-10-23 05:50

import django.utils.timezone
import medical_data.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=medical_data.models.medical_json_file_path, validators=[medical_data.models.validate_json_extension], verbose_name='JSON файл')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('height', models.FloatField(verbose_name='Рост (см)')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('blood_pressure', models.CharField(max_length=10, verbose_name='Артериальное давление')),
                ('heart_rate', models.PositiveIntegerField(verbose_name='Частота сердечных сокращений')),
                ('temperature', models.FloatField(verbose_name='Температура тела (°C)')),
                ('symptoms', models.TextField(verbose_name='Симптомы')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='Диагноз')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_source', models.CharField(choices=[('db', 'База данных'), ('file', 'Файл')], default='db', max_length=10)),
            ],
        ),
    ]
